alloy:
  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  configMap:
    # -- Create a new ConfigMap for the config file.
    create: true
    # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
    content: |-
      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.loki.receiver]
      }

      loki.write "loki" {
        endpoint {
          url = "http://loki-distributor.loki.svc.cluster.local:3100/loki/api/v1/push"
        }
        
        external_labels = { 
          cluster = "grafana-cluster",
        }
      }

      otelcol.receiver.otlp "default" {
        grpc {}
        http {}

        output {
          traces = [otelcol.processor.k8sattributes.default.input]
        }
      }

      otelcol.processor.k8sattributes "default" {
        extract {
          metadata = [
            "k8s.namespace.name",
            "k8s.pod.name",
            ]
        }

        output {
          traces = [otelcol.exporter.otlp.default.input]
        }
      }

      otelcol.exporter.otlp "default" {
        client {
          endpoint = "tempo-distributor.tempo.svc.cluster.local:4317"

          tls {
            insecure = true
          }
        }
      }
