apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: grafana
  labels:
    grafana_datasource: "true"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: "http://prometheus-server.prometheus.svc.cluster.local"
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: "http://loki-query-frontend.loki.svc.cluster.local:3100"
      - name: Tempo
        type: tempo
        access: proxy
        url: "http://tempo-query-frontend.tempo.svc.cluster.local:3100"
